language: python
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"


# command to run tests
script:
   - nosetests --with-coverage --cover-tests
   - coverage report

# Another method to run tests
script: 
  - pytest

after_success:
- coveralls
